#!/usr/bin/env bash
# Assemble the RTRREMOTE NextUI PAK for the Trimui (tg5050).
#
# Runs on the dev machine (x86_64) and cross-builds the device PAK:
#   1. python-build-standalone aarch64  -> dist/RTRREMOTE.pak/python/
#   2. pygame + websockets wheels (aarch64) -> dist/RTRREMOTE.pak/venv/lib/
#   3. DejaVuSansMono.ttf               -> dist/RTRREMOTE.pak/fonts/
#   4. config.json defaults            -> dist/RTRREMOTE.pak/config.json
#   5. the lean Python app code (closure of rtr.remote.sdlapp) -> dist/repo/
#
# The PAK (python/ + venv/ + fonts/ + config) is ~200MB and is the part that is
# slow to scp. The app code is a few hundred KB and is staged separately in
# dist/repo/, so code updates can be shipped WITHOUT re-sending the PAK.
#
# Then copy the finished folder to the SD card:  Tools/tg5050/RTRREMOTE.pak/
#
# Usage:
#   scripts/build_pak.sh            # assemble static parts (fonts + config + code)
#   scripts/build_pak.sh --full     # also download python/ + venv/ (network)
#   scripts/build_pak.sh --ship-code# scp ONLY the app code to the device
#
# Env overrides (for pinning / offline builds / device target):
#   PBS_URL        exact python-build-standalone aarch64 tarball URL
#   PBS_TARBALL    path to a pre-downloaded pb-s aarch64 tarball (skips curl)
#   FONT_SRC       path to DejaVuSansMono.ttf (default: <repo>/fonts or /usr/share)
#   VENV_SITE      target site-packages dir under the PAK (default: venv/lib/python3.11/site-packages)
#   DEVICE         scp/ssh target for --ship-code (default: root@192.168.1.33)
#   REPO_PATH      on-device app-code dir (default: /storage/rtr-remote; matches config.json "repo")
set -euo pipefail

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
PKG_DIR=$(cd "$SCRIPT_DIR/.." && pwd)                 # realtimecontrol/rtr
PAK_DIR="$PKG_DIR/pak/RTRREMOTE.pak"
DIST_DIR="$PKG_DIR/dist/RTRREMOTE.pak"                 # build output (copy-ready)
REPO_STAGE="$PKG_DIR/dist/repo"                        # lean app-code artifact (copy-ready)

# Device target (no git/rsync on the device; ship over ssh/scp). Overridable.
DEVICE=${DEVICE:-root@192.168.1.33}
REPO_PATH=${REPO_PATH:-/storage/rtr-remote}            # matches config.json "repo"
PAK_DEVICE_PATH=${PAK_DEVICE_PATH:-/mnt/SDCARD/Tools/tg5050/RTRREMOTE.pak}  # where the PAK lives on the device

FULL=0
SHIP_CODE=0
for arg in "$@"; do
    case "$arg" in
        --full)      FULL=1 ;;
        --ship-code) SHIP_CODE=1 ;;
        *) echo "unknown flag: $arg (expected --full and/or --ship-code)"; exit 2 ;;
    esac
done
# --ship-code alone only pushes the app code; do NOT wipe/rebuild the ~200MB PAK.
DO_PAK=1
if [ $# -eq 1 ] && [ "$1" = "--ship-code" ]; then DO_PAK=0; fi

# Pinned python-build-standalone aarch64 release. The current release layout
# (astral-sh) names assets:  cpython-<ver>+<tag>-aarch64-unknown-linux-gnu-install_only.tar.gz
# and the archive extracts to a top-level ``python/`` dir. Verify the exact
# asset for your tag at: https://github.com/astral-sh/python-build-standalone/releases
PBS_TAG=${PBS_TAG:-20261003}
CPYTHON_VER=${CPYTHON_VER:-3.11.17}
PBS_URL=${PBS_URL:-"https://github.com/astral-sh/python-build-standalone/releases/download/${PBS_TAG}/cpython-${CPYTHON_VER}+${PBS_TAG}-aarch64-unknown-linux-gnu-install_only.tar.gz"}
VENV_SITE=${VENV_SITE:-"venv/lib/python3.11/site-packages"}

echo "==> PAK output: $DIST_DIR"

# ---------------------------------------------------------------------------
# 0. Fresh build tree (static parts always; python/venv only with --full).
#    --ship-code alone keeps any existing PAK (no wipe) and only re-stages code.
# ---------------------------------------------------------------------------
if [ "$DO_PAK" -eq 1 ]; then
    rm -rf "$DIST_DIR"
fi
rm -rf "$REPO_STAGE"
mkdir -p "$DIST_DIR/fonts" "$DIST_DIR/$VENV_SITE" "$REPO_STAGE"

# ---------------------------------------------------------------------------
# 1. launch.sh + config.json + icon.png (static, from the repo PAK).
# ---------------------------------------------------------------------------
cp "$PAK_DIR/launch.sh" "$DIST_DIR/launch.sh"
chmod +x "$DIST_DIR/launch.sh"

# NextUI launcher icon. Generated by scripts/make_icon.py; if absent, regenerate.
if [ -f "$PAK_DIR/icon.png" ]; then
    cp "$PAK_DIR/icon.png" "$DIST_DIR/icon.png"
else
    echo "icon.png missing; regenerating via scripts/make_icon.py"
    python3 "$SCRIPT_DIR/make_icon.py" "$PAK_DIR/icon.png" >/dev/null 2>&1 || true
    [ -f "$PAK_DIR/icon.png" ] && cp "$PAK_DIR/icon.png" "$DIST_DIR/icon.png"
fi

if [ -f "$PAK_DIR/config.json" ]; then
    cp "$PAK_DIR/config.json" "$DIST_DIR/config.json"
else
    echo "config.json missing; writing defaults"
    cat > "$DIST_DIR/config.json" <<'JSON'
{
  "core_host": "127.0.0.1",
  "core_port": 8765,
  "http_port": 8766,
  "device": "auto",
  "chord_window_ms": 200,
  "width": 320,
  "screen_height": 240,
  "font": "fonts/DejaVuSansMono.ttf",
  "font_size": 16,
  "repo": "/storage/rtr-remote",
  "joy_map": {
    "15": "up", "16": "down", "17": "left", "18": "right",
    "29": "enter", "30": "q", "8": "h",
    "310": "left", "311": "right"
  },
  "theme": {
    "bg": "#000000", "bar": "#ffff00", "bar_bg": "#000080",
    "conn_ok": "#00ff00", "conn_bad": "#ff0000", "page": "#808000",
    "divider": "#808000", "status": "#808000", "label": "#ffff00",
    "state_val": "#ffffff", "item": "#c0c0c0", "item_sel": "#000000",
    "item_sel_bg": "#ffff00", "item_dim": "#606060", "help": "#606060",
    "feral": "#ff0000", "text": "#c0c0c0"
  }
}
JSON
fi
echo "==> launch.sh + config.json"

# ---------------------------------------------------------------------------
# 2. Font (DejaVuSansMono covers <- -> ~ ▸ # and digits).
# ---------------------------------------------------------------------------
FONT_SRC=${FONT_SRC:-}
if [ -z "$FONT_SRC" ]; then
    for cand in "$PAK_DIR/fonts/DejaVuSansMono.ttf" \
                /usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf; do
        [ -f "$cand" ] && FONT_SRC="$cand" && break
    done
fi
if [ -n "$FONT_SRC" ] && [ -f "$FONT_SRC" ]; then
    cp "$FONT_SRC" "$DIST_DIR/fonts/DejaVuSansMono.ttf"
    echo "==> font: $FONT_SRC"
else
    echo "!! FONT_SRC not found; copy DejaVuSansMono.ttf into $DIST_DIR/fonts/ manually"
fi

# ---------------------------------------------------------------------------
# 3. python-build-standalone aarch64  ->  python/
# ---------------------------------------------------------------------------
if [ "$FULL" -eq 1 ]; then
    STAGE=$(mktemp -d)
    if [ -n "${PBS_TARBALL:-}" ] && [ -f "$PBS_TARBALL" ]; then
        echo "==> extracting pb-s from $PBS_TARBALL"
        tar -xzf "$PBS_TARBALL" -C "$STAGE"
    else
        echo "==> downloading pb-s aarch64:"
        echo "    $PBS_URL"
        curl -fL -# -o "$STAGE/pbs-aarch64.tar.gz" "$PBS_URL"
        tar -xzf "$STAGE/pbs-aarch64.tar.gz" -C "$STAGE"
        rm -f "$STAGE/pbs-aarch64.tar.gz"
    fi
    # The install_only tarball has a top-level python/ dir; move it into the PAK.
    if [ -d "$STAGE/python" ]; then
        rm -rf "$DIST_DIR/python"
        mv "$STAGE/python" "$DIST_DIR/python"
    else
        echo "!! unexpected tarball layout (no top-level python/); found:"
        ls "$STAGE"; rm -rf "$STAGE"; exit 1
    fi
    rm -rf "$STAGE"
    ls "$DIST_DIR/python/bin/python3" >/dev/null 2>&1 || {
        echo "!! expected python/bin/python3 under $DIST_DIR/python"; ls "$DIST_DIR/python"; exit 1; }
    echo "==> python/ (aarch64)"
else
    echo "==> skipping python/ (run with --full, or copy a prepared python/ in)"
fi

# ---------------------------------------------------------------------------
# 4. pygame + websockets wheels (aarch64)  ->  venv/lib
# ---------------------------------------------------------------------------
if [ "$FULL" -eq 1 ]; then
    WHEEL_TMP=$(mktemp -d)
    echo "==> downloading aarch64 wheels (manylinux2014_aarch64, py3.11)"
    python3 -m pip download --only-binary=:all: \
        --platform manylinux2014_aarch64 \
        --python-version 311 \
        --cache-dir "$WHEEL_TMP/.pipcache" \
        -d "$WHEEL_TMP" \
        pygame "websockets>=12,<14"
    # Unpack each wheel (a zip) into the site-packages dir.
    for w in "$WHEEL_TMP"/*.whl; do
        [ -e "$w" ] || continue
        echo "    $(basename "$w")"
        unzip -q "$w" -d "$DIST_DIR/$VENV_SITE"
    done
    rm -rf "$WHEEL_TMP"
    # pygame bundles SDL2 under a top-level pygame.libs/ dir (hashed .so names);
    # verify it landed.
    ls "$DIST_DIR/$VENV_SITE"/pygame.libs >/dev/null 2>&1 || {
        echo "!! pygame.libs (bundled SDL2) not found under venv"; exit 1; }
    echo "==> venv/lib (aarch64 wheels)"
else
    echo "==> skipping venv/ (run with --full, or copy a prepared venv/ in)"
fi

# ---------------------------------------------------------------------------
# 5. Lean Python app code (closure of rtr.remote.sdlapp)  ->  dist/repo/
# ---------------------------------------------------------------------------
# The exact files the SDL app imports at runtime. `rtr/remote/__init__.py` pulls
# in tui.py, but tui.py guards `import urwid` (urwid=None if absent), so no
# extra runtime libs are needed. Kept tiny so it can be scp'd alone.
CODE_FILES=(
    "rtr/__init__.py"
    "rtr/flow.py"
    "rtr/remote/__init__.py"
    "rtr/remote/sdlapp.py"
    "rtr/remote/view.py"
    "rtr/remote/config.py"
    "rtr/remote/connection.py"
    "rtr/remote/events.py"
    "rtr/remote/tui.py"
)
for f in "${CODE_FILES[@]}"; do
    src="$PKG_DIR/$f"
    [ -f "$src" ] || { echo "!! missing app-code file: $src"; exit 1; }
    mkdir -p "$REPO_STAGE/$(dirname "$f")"
    cp "$src" "$REPO_STAGE/$f"
done
echo "==> app code: $(find "$REPO_STAGE" -type f | wc -l) files staged in $REPO_STAGE"

# ---------------------------------------------------------------------------
# 6. Ship ONLY the app code to the device (no git/rsync on the device).
#    We stream the tree over ssh via tar: it needs no rsync, creates the
#    destination atomically, and avoids the OpenSSH 9.x scp directory
#    "path canonicalization failed" error that plain `scp -r` hits.
# ---------------------------------------------------------------------------
if [ "$SHIP_CODE" -eq 1 ]; then
    echo "==> shipping app code -> $DEVICE:$REPO_PATH (PAK not re-sent)"
    # Fail fast if the destination isn't a real, writable path on the device.
    if ! ssh "$DEVICE" "mkdir -p '$REPO_PATH' && test -d '$REPO_PATH'"; then
        echo "!! could not create/verify $REPO_PATH on $DEVICE."
        echo "   The on-device SD card is mounted at /mnt/SDCARD/; the default"
        echo "   /storage path may not exist. Try:"
        echo "       REPO_PATH=/mnt/SDCARD/rtr-remote $0 --ship-code"
        echo "   Whatever path you use, set the SAME path in the PAK's"
        echo "   config.json \"repo\" field so launch.sh finds the code."
        exit 1
    fi
    # Stream the rtr/ tree over ssh; extract into REPO_PATH on the device.
    if tar -C "$REPO_STAGE" -cf - rtr | ssh "$DEVICE" "tar -C '$REPO_PATH' -xf -"; then
        echo "==> shipped via tar-over-ssh"
    else
        echo "!! tar-over-ssh failed. Retry by hand (dir already created):"
        echo "    scp -r $REPO_STAGE/rtr $DEVICE:$REPO_PATH/"
        exit 1
    fi
    echo "==> done. On-device self-test (uses the PAK's bundled python):"
    echo "    ssh $DEVICE \"$PAK_DEVICE_PATH/launch.sh --selftest\""
fi

# ---------------------------------------------------------------------------
# 7. Summary + copy instructions.
# ---------------------------------------------------------------------------
echo
echo "==> PAK assembled at:  $DIST_DIR   (~200MB, send once)"
echo "==> app code staged at: $REPO_STAGE   (tiny, send for updates)"
echo
echo "Copy the PAK once (slow over wifi):"
echo "    scp -r $DIST_DIR $DEVICE:/mnt/SDCARD/Tools/tg5050/"
echo
echo "Ship ONLY the python app code (fast, code updates):"
echo "    $0 --ship-code"
echo "    #  =  ssh $DEVICE \"mkdir -p '$REPO_PATH'\" && scp -r $REPO_STAGE/rtr $DEVICE:$REPO_PATH/"
echo
echo "Then on-device:"
echo "    /mnt/SDCARD/Tools/tg5050/RTRREMOTE.pak/launch.sh --selftest"
